# Generated by Django 6.1 on 2026-10-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0009_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='number_of_semesters',
            field=models.PositiveIntegerField(default=8),
        ),
    ]
