# Generated by Django 6.1 on 2026-10-04 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0010_courses_number_of_semesters'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='current_semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_management_app.semester'),
        ),
    ]
