# Generated by Django 6.1 on 2026-10-06 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0011_students_current_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='current_semester',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='number_of_semesters',
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
    ]
