# Generated by Django 6.1 on 2026-10-06 17:27

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0012_remove_students_current_semester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfee',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='fee_period',
            field=models.DateField(default=datetime.date(2026, 10, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentfee',
            name='paid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.students'),
        ),
    ]
