# Generated by Django 6.1 on 2026-10-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0014_alter_attendancereport_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavereportstudent',
            name='leave_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
